server:
  # 端口设置
  port: 8080
  servlet:
    context-path: /

# Spring配置
spring:
  profiles: prod
  datasource:
    # 如果存在多个数据源，监控的时候可以通过名字来区分开来
    name: mysql
    # 连接数据库的url
    url: jdbc:mysql://localhost:3306/personnelsystem?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    # 连接数据库的账号
    username: root
    # 连接数据库的密码
    password: 130106
  # 开启热部署
  devtools:
    restart:
      enabled: true


# 日志配置
logging:
  # 日志输出级别
  level:
    ROOT: info

# 自评报告
upload:
  img:
    path: E:\photo\